spring:
  application:
    name: CONFIG-SERVER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9002/eureka/
  instance:
    hostname: localhost
